---
- name: Archlinux | Check if .zshrc exists.
  stat:
    path: ~/.zshrc
  register: stat_rc_result

- name: Archlinux | Check if .oh-my-zsh exists.
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result

- name: Archlinux | Check if /root/.oh-my-zsh exists.
  become: true
  stat:
    path: /root/.oh-my-zsh
  register: stat_root_oh_my_zsh_result

- name: Archlinux | Cloning oh-my-zsh to user.
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists

- name: Archlinux | Cloning oh-my-zsh to root.
  become: true
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=/root/.oh-my-zsh
  when: not stat_root_oh_my_zsh_result.stat.exists

- name: Archlinux | Creating new ~/.zshrc.
  copy:
    src=~/.oh-my-zsh/templates/zshrc.zsh-template
    dest=~/.zshrc
  when: not stat_rc_result.stat.exists